#!/usr/bin/env bash

# Modified copy of "set_demo_current_vel" in package "uuv_plume_simulator"
# Full filepath: catkin_ws/src/uuv_plume_simulator/uuv_plume_simulator/scripts/set_demo_current_vel

rosservice call /hydrodynamics/set_current_velocity_model "{mean: 1.0, min: 0.8, max: 1.2, noise: 0.01, mu: 0.05}"
rosservice call /hydrodynamics/set_current_horz_angle_model "{mean: -0.785, min: -0.8, max: -0.7, noise: 0.01, mu: 0.05}"