#!/usr/bin/env bash

# Modified copy of "set_demo_turbulent_plume" in package "uuv_plume_simulator"
# Full filepath: catkin_ws/src/uuv_plume_simulator/uuv_plume_simulator/scripts/set_demo_turbulent_plume

rosservice call /plume/create_passive_scalar_turbulent_plume "turbulent_diffusion_coefficients: {x: 0.05, y: 0.05, z: 0.05}
source: {x: -30.0, y: 15.0, z: -25.0}
buoyancy_flux: 0.05
stability_param: 0.001
n_points: 100000
max_particles_per_iter: 1
x_min: -200.0
x_max: 200.0
y_min: -75.0
y_max: 75.0
z_min: -50.0
z_max: 0.0
max_life_time: -1"